const Examdata = [
  {
    img: "https://images.collegedunia.com/public/college_data/images/logos/NTA- Logo.png?h=44&w=44&mode=stretch",
    examtype: "Offline Exam",
    examname: "NEET",
    participatingcolleges: "892",
    examdate: "May 05, 2024",
    examlevel: "national",
  },
  {
    img: "https://images.collegedunia.com/public/college_data/images/logos/iitm (1).jpg?h=44&w=44&mode=stretch",
    examtype: "Online Exam",
    examname: "JEE Advanced",
    participatingcolleges: "55",
    examdate: "May 26, 2024",
    examlevel: "national",
  },
  {
    img: "https://images.collegedunia.com/public/college_data/images/logos/NTA Logo.jpg?h=44&w=44&mode=stretch",
    examtype: "Online Exam",
    examname: "JEE Main",
    participatingcolleges: "1706",
    examdate: "April 04, 2024",
    examlevel: "national",
  },
  {
    img: "https://images.collegedunia.com/public/college_data/images/logos/CAT logo.jpg?h=44&w=44&mode=stretch",
    examtype: "Online Exam",
    examname: "CAT",
    participatingcolleges: "1476",
    examdate: "November 26, 2023",
    examlevel: "national",
  },
  {
    img: "https://images.collegedunia.com/public/college_data/images/logos/MAT Exam Logo.jpg?h=44&w=44&mode=stretch",
    examtype: "Online + Offline Exam",
    examname: "MAT",
    participatingcolleges: "1332",
    examdate: "June 02, 2024",
    examlevel: "national",
  },
  {
    img: "https://images.collegedunia.com/public/college_data/images/logos/iisc-hdr-logo.jpg?h=44&w=44&mode=stretch",
    examtype: "Online Exam",
    examname: "GATE",
    participatingcolleges: "1381",
    examdate: "February 03, 2024",
    examlevel: "national",
  },
  {
    img: "https://images.collegedunia.com/public/college_data/images/logos/Capture.JPG?h=44&w=44&mode=stretch",
    examtype: "Online Exam",
    examname: "NMAT",
    participatingcolleges: "117",
    examdate: "October 10, 2023",
    examlevel: "national",
  },
  {
    img: "https://images.collegedunia.com/public/college_data/images/logos/XAT_0.jpg?h=44&w=44&mode=stretch",
    examtype: "Online Exam",
    examname: "XAT",
    participatingcolleges: "855",
    examdate: "January 07, 2024",
    examlevel: "national",
  },
  {
    img: "https://images.collegedunia.com/public/college_data/images/logos/BITS Pilani Logo.png?h=44&w=44&mode=stretch",
    examtype: "Online Exam",
    examname: "BITSAT",
    participatingcolleges: "3",
    examdate: "June 22, 2024",
    examlevel: "national",
  },
  {
    img: "https://images.collegedunia.com/public/college_data/images/logos/iit madras.png?h=44&w=44&mode=stretch",
    examtype: "Online Exam",
    examname: "IIT JAM",
    participatingcolleges: "51",
    examdate: "February 11, 2024",
    examlevel: "national",
  },
];

export default Examdata;